# Generated by Django 4.0.4 on 2022-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques', models.CharField(max_length=150)),
                ('Ans', models.TextField()),
            ],
        ),
    ]
