# Generated by Django 4.0.4 on 2022-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Ques',
            field=models.TextField(max_length=150),
        ),
    ]
