# Generated by Django 4.0.4 on 2022-05-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='fullname',
            new_name='full_Name',
        ),
    ]
