# Generated by Django 4.0.4 on 2022-05-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gallery_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subplan')),
            ],
        ),
    ]
