# Generated by Django 4.0.4 on 2022-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_subplanfeature_subplan_subplanfeature_subplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(to='app.subplan'),
        ),
    ]
