# Generated by Django 4.0.4 on 2022-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_subplanfeature_subplan_subplanfeature_subplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlights_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
