# Generated by Django 4.0.4 on 2022-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_plandiscout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandiscout',
            name='subplan',
        ),
        migrations.AddField(
            model_name='plandiscout',
            name='subplan',
            field=models.ManyToManyField(to='app.subplan'),
        ),
    ]
