# Generated by Django 4.0.4 on 2022-05-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_plandiscout_subplan_plandiscout_subplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanDiscout',
            new_name='PlanDiscount',
        ),
    ]
